# Generated by Django 4.2 on 2025-09-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_Code', models.CharField(max_length=10)),
                ('College_Name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('taluka', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('college_type', models.CharField(max_length=50)),
                ('belongs_to', models.CharField(max_length=40)),
                ('affiliated', models.CharField(max_length=50)),
                ('discipline', models.CharField(max_length=50)),
            ],
        ),
    ]
