# Generated by Django 4.2 on 2025-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='address',
            field=models.TextField(),
        ),
    ]
