# Generated by Django 4.2 on 2025-09-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0002_colleges_is_deleted_alter_colleges_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='created_by',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colleges',
            name='updated_by',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
