# Generated by Django 4.2.24 on 2025-09-24 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0003_colleges_created_by_colleges_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='colleges',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='colleges',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
