# Generated by Django 4.2.24 on 2025-09-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0004_colleges_created_at_colleges_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
