# Generated by Django 4.2.24 on 2025-09-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0006_colleges_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
