# Generated by Django 4.2.24 on 2025-10-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0007_alter_colleges_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_Code', models.CharField(max_length=10)),
                ('College_Name', models.CharField(max_length=80)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('taluka', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=10)),
                ('college_type', models.CharField(max_length=50)),
                ('belongs_to', models.CharField(max_length=40)),
                ('affiliated', models.CharField(max_length=50)),
                ('created_by', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discipline', models.CharField(max_length=50)),
                ('ProgramName', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('College', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_programs', to='College_records_app.college')),
            ],
            options={
                'unique_together': {('Discipline', 'ProgramName')},
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisciplineName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DistrictName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProgramName', models.CharField(max_length=50)),
                ('Discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='College_records_app.discipline')),
            ],
            options={
                'unique_together': {('Discipline', 'ProgramName')},
            },
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TalukaName', models.CharField(max_length=50)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talukas', to='College_records_app.district')),
            ],
            options={
                'unique_together': {('District', 'TalukaName')},
            },
        ),
        migrations.DeleteModel(
            name='Colleges',
        ),
    ]
