# Generated by Django 4.2.24 on 2025-10-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0008_college_collegeprogram_discipline_district_programs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='ProgramName',
            field=models.CharField(max_length=150),
        ),
    ]
