# Generated by Django 4.2.24 on 2025-10-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0009_alter_programs_programname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BelongsTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BelongsToName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollegeTypeName', models.CharField(max_length=50)),
            ],
        ),
    ]
