# Generated by Django 4.2.24 on 2025-10-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0010_belongsto_collegetype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collegeprogram',
            unique_together={('College', 'Discipline', 'ProgramName')},
        ),
    ]
