# Generated by Django 4.2.24 on 2025-11-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0011_alter_collegeprogram_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='academic_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Academic_Year', models.CharField(max_length=20)),
            ],
        ),
    ]
