# Generated by Django 4.2.24 on 2025-11-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0012_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_aggregate_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Academic_Year', models.CharField(max_length=20)),
                ('total_students', models.IntegerField(default=0)),
                ('total_male', models.IntegerField(default=0)),
                ('total_female', models.IntegerField(default=0)),
                ('total_others', models.IntegerField(default=0)),
                ('total_open', models.IntegerField(default=0)),
                ('total_obc', models.IntegerField(default=0)),
                ('total_sc', models.IntegerField(default=0)),
                ('total_st', models.IntegerField(default=0)),
                ('total_nt', models.IntegerField(default=0)),
                ('total_vjnt', models.IntegerField(default=0)),
                ('total_ews', models.IntegerField(default=0)),
                ('total_hindu', models.IntegerField(default=0)),
                ('total_muslim', models.IntegerField(default=0)),
                ('total_sikh', models.IntegerField(default=0)),
                ('total_christian', models.IntegerField(default=0)),
                ('total_jain', models.IntegerField(default=0)),
                ('total_buddhist', models.IntegerField(default=0)),
                ('total_other_religion', models.IntegerField(default=0)),
                ('total_no_disability', models.IntegerField(default=0)),
                ('total_low_vision', models.IntegerField(default=0)),
                ('total_blindness', models.IntegerField(default=0)),
                ('total_hearing', models.IntegerField(default=0)),
                ('total_locomotor', models.IntegerField(default=0)),
                ('total_autism', models.IntegerField(default=0)),
                ('total_other_disability', models.IntegerField(default=0)),
                ('created_by', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('College', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_aggregates', to='College_records_app.college')),
                ('Program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_aggregates', to='College_records_app.collegeprogram')),
            ],
            options={
                'unique_together': {('College', 'Program', 'Academic_Year')},
            },
        ),
    ]
