# Generated by Django 4.2.24 on 2025-11-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0013_student_aggregate_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='belongs_to',
            field=models.CharField(max_length=50),
        ),
    ]
