# Generated by Django 4.2.24 on 2025-11-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0014_alter_college_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='affiliated',
            field=models.CharField(max_length=55),
        ),
    ]
