# Generated by Django 4.2.24 on 2025-11-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0015_alter_college_affiliated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student_aggregate_master',
            unique_together={('College', 'Program', 'Academic_Year', 'is_deleted')},
        ),
    ]
