# Generated by Django 4.2.24 on 2025-11-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0017_rename_total_autism_student_aggregate_master_autism_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='Female_Washrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='Male_Washrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college',
            name='total_washrooms',
            field=models.IntegerField(default=0),
        ),
    ]
