# Generated by Django 4.2.24 on 2025-11-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0018_college_female_washrooms_college_male_washrooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='Female_Washrooms',
            new_name='female_washrooms',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='Male_Washrooms',
            new_name='male_washrooms',
        ),
    ]
