# Generated by Django 4.2.24 on 2025-11-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0019_rename_female_washrooms_college_female_washrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_aggregate_master',
            name='female_washrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_aggregate_master',
            name='male_washrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student_aggregate_master',
            name='total_washrooms',
            field=models.IntegerField(default=0),
        ),
    ]
