# Generated by Django 4.2.24 on 2025-12-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College_records_app', '0020_student_aggregate_master_female_washrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='female_washrooms',
        ),
        migrations.RemoveField(
            model_name='college',
            name='male_washrooms',
        ),
        migrations.RemoveField(
            model_name='college',
            name='total_washrooms',
        ),
    ]
