# Generated by Django 4.2.24 on 2025-12-05 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('College_records_app', '0022_staff_master_aggregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='College_records_app.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
